name: CI on PR

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    name: Run tests on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
